"""
Shared matplotlib settings and constants for all reproduce_plots scripts.
"""

import sys
import os
from pathlib import Path
from cycler import cycler

import numpy as np
import matplotlib.pyplot as plt

# ── Workspace root (one level up from this file) ─────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
# Add root to sys.path so plot_utils and other modules are importable
sys.path.insert(0, str(ROOT))

# ── Data directories ──────────────────────────────────────────────────────────
# Original full data (segwo_results, data/)
DATA_DIR = ROOT / "data"
SEGWO_DIR = ROOT / "segwo_results"
# Lightweight extracted HDF5 files (generated by save_all_data.py)
EXTRACTED_DIR = Path(__file__).resolve().parent / "data"
EXTRACTED_DIR.mkdir(exist_ok=True)
# Output directory for reproduced figures
OUTPUT_DIR = Path(__file__).resolve().parent / "figures"
OUTPUT_DIR.mkdir(exist_ok=True)

# ── Colorblind-friendly palette (Wong 2011) ───────────────────────────────────
COLORBLIND_PALETTE = [
    "#E69F00",  # orange
    "#56B4E9",  # sky blue
    "#009E73",  # bluish green
    "#F0E442",  # yellow
    "#0072B2",  # blue
    "#D55E00",  # vermillion
    "#CC79A7",  # reddish purple
]

# ── Figure width constants (inches) ──────────────────────────────────────────
COL1 = 3.5   # single-column
COL2 = 7.2   # double-column

# ── Polarisation labels ───────────────────────────────────────────────────────
POLS = (r'$h_+$', r'$h_\times$')

# ── Matplotlib settings ───────────────────────────────────────────────────────
def apply_style():
    plt.rcParams.update({
        'text.usetex':       True,
        'font.family':       'times',
        'font.size':         9,
        'axes.labelsize':    9,
        'axes.titlesize':    9,
        'xtick.labelsize':   8,
        'ytick.labelsize':   8,
        'legend.fontsize':   8,
        'legend.frameon':    True,
        'legend.framealpha': 0.8,
        'figure.dpi':        150,
        'savefig.dpi':       300,
        'savefig.bbox':      'tight',
        'axes.grid':         True,
        'grid.alpha':        0.3,
        'grid.linestyle':    ':',
        'lines.linewidth':   1.5,
        'axes.spines.top':   False,
        'axes.spines.right': False,
        'axes.prop_cycle':   cycler('color', COLORBLIND_PALETTE),
    })
