"""
Plot 02 — Static orbit perturbation distributions.

Histograms of LTT residuals (arm-length perturbation), spacecraft position
residuals (translation perturbation), and constellation tilt angle
(rotation perturbation).

Requires:
  reproduce_plots/data/perturbation_data.h5   (generated by save_all_data.py)

Output:
  reproduce_plots/figures/static_orbit_perturbation_distributions.pdf
"""

from pathlib import Path
import sys
import numpy as np
import h5py
import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from config import apply_style, EXTRACTED_DIR, OUTPUT_DIR, COL2
from lisaconstants.indexing import LINKS
from lisaconstants import C

apply_style()

# ── Load data ─────────────────────────────────────────────────────────────────
with h5py.File(EXTRACTED_DIR / "perturbation_data.h5", "r") as ds:
    ltt_residuals      = ds["arm_boost/ltt_residuals"][()]
    position_residuals = ds["translation_boost/position_residuals"][()]
    angle              = ds["rotation_boost/angle"][()]

# ── Plot ──────────────────────────────────────────────────────────────────────
linestyle = ['-', '--', '-.']

fig, axes = plt.subplots(1, 3, figsize=(COL2, 2.4))

# LTT residuals
ax = axes[0]
for i in range(3):
    ax.hist(
        ltt_residuals[:, i], bins=25,
        histtype='step', linestyle=linestyle[i], linewidth=1.5, density=True,
        label=rf"$ij = {{{LINKS[i]}}}$",
    )
ax.set_xlabel(r"$\Delta L_{ij}$ [s]")
ax.set_ylabel("Density")
ax.axvline(1.0 / C, color='tab:red', ls='--', lw=1.2)
ax.set_yticklabels([])
ax.set_title("Light Travel Time")
ax.legend()

# Position residuals (SC 1)
ax = axes[1]
for i, lbl in enumerate(["$x$", "$y$", "$z$"]):
    ax.hist(
        position_residuals[:, 0, i] / 1e3, bins=25,
        histtype='step', linestyle=linestyle[i], linewidth=1.5, density=True,
        label=lbl,
    )
ax.set_xlabel(r"$\Delta \mathbf{r}$ [km]")
ax.set_yticklabels([])
ax.axvline(50.0, color='tab:red', ls='--', lw=1.2)
ax.set_title("Spacecraft 1 Position")
ax.legend()

# Constellation tilt angle
ax = axes[2]
dist_centroid  = 2.5e9 * np.sqrt(1 / 3)
expected_sigma = 50e3 * 2.13 / dist_centroid
ax.hist(angle, bins=25, histtype='step', linewidth=1.5, density=True)
ax.axvline(expected_sigma, color='tab:red', ls='--', lw=1.2, label=r"Reference $\sigma$")
ax.set_xlabel(r"$\Delta\phi$ [rad]")
ax.set_yticklabels([])
ax.set_title("Constellation tilt angle")
ax.legend()

plt.tight_layout()
out = OUTPUT_DIR / "static_orbit_perturbation_distributions.pdf"
plt.savefig(out)
print(f"✓ {out.name}")
plt.show()
