"""
Plot 03 — Evolving (realistic) orbit perturbation distributions.

Histograms of LTT residuals, spacecraft position residuals, and
constellation tilt angle for the 15-day evolving (realistic) orbit case.

Requires:
  reproduce_plots/data/perturbation_data.h5   (generated by save_all_data.py)

Output:
  reproduce_plots/figures/evolving_orbit_perturbation_distributions.pdf
"""

from pathlib import Path
import sys
import numpy as np
import h5py
import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from config import apply_style, EXTRACTED_DIR, OUTPUT_DIR, COL2
from lisaconstants.indexing import LINKS

apply_style()

# ── Load data ─────────────────────────────────────────────────────────────────
with h5py.File(EXTRACTED_DIR / "perturbation_data.h5", "r") as ds:
    ltt_residuals      = ds["realistic_boost/ltt_residuals"][()]
    position_residuals = ds["realistic_boost/position_residuals"][()]
    angle              = ds["realistic_boost/angle"][()]

# ── Plot ──────────────────────────────────────────────────────────────────────
linestyle = ['-', '--', '-.']

fig, axes = plt.subplots(1, 3, figsize=(COL2, 2.4))

# LTT residuals
ax = axes[0]
for i in range(3):
    ax.hist(
        ltt_residuals[:, i], bins=25,
        histtype='step', linestyle=linestyle[i], linewidth=1.5, density=True,
        label=rf"$ij = {{{LINKS[i]}}}$",
    )
ax.set_xlabel(r"$\Delta L_{ij}$ [s]")
ax.set_ylabel("Density")
ax.set_yticklabels([])
ax.set_title("Light Travel Time")
ax.legend()

# Position residuals (SC 1)
ax = axes[1]
for i, lbl in enumerate(["$x$", "$y$", "$z$"]):
    ax.hist(
        position_residuals[:, 0, i] / 1e3, bins=25,
        histtype='step', linestyle=linestyle[i], linewidth=1.5, density=True,
        label=lbl,
    )
ax.set_xlabel(r"$\Delta \mathbf{r}$ [km]")
ax.set_yticklabels([])
ax.set_title("Spacecraft 1 Position")
ax.legend()

# Constellation tilt angle
ax = axes[2]
ax.hist(angle, bins=25, histtype='step', linewidth=1.5, density=True)
ax.set_xlabel(r"$\Delta\phi$ [rad]")
ax.set_yticklabels([])
ax.set_title("Constellation tilt angle")

plt.tight_layout()
out = OUTPUT_DIR / "evolving_orbit_perturbation_distributions.pdf"
plt.savefig(out)
print(f"✓ {out.name}")
plt.show()
