"""
Plot 08 — Galactic Binary mismatch comparison.

Overlays:
  • GB mismatch vs f0 (sky-averaged) from gb_mismatch_results_15.0days.h5
  • Mismatch at best-fit from gb_bias_results_15.0days.h5
  • Response-only (no GB signal) realistic mismatch from gb_segwo_mismatch.h5

Requires:
  <workspace_root>/data/gb_mismatch_results_15.0days.h5   (already lightweight)
  <workspace_root>/data/gb_bias_results_15.0days.h5       (already lightweight)
  reproduce_plots/data/gb_segwo_mismatch.h5               (generated by save_all_data.py)

Output:
  reproduce_plots/figures/gb_mismatch_plot.png
"""

from pathlib import Path
import sys
import numpy as np
import h5py
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from config import apply_style, DATA_DIR, EXTRACTED_DIR, OUTPUT_DIR, COL1

apply_style()

# ── Load GB mismatch data ─────────────────────────────────────────────────────
mismatch = {}
with h5py.File(DATA_DIR / "gb_mismatch_results_15.0days.h5", "r") as fh:
    f0_vec = fh["f0_vec"][()]
    for key in fh.keys():
        if key.startswith("mismatch_"):
            mismatch[key] = fh[key][()]

# ── Load bias / best-fit mismatch ─────────────────────────────────────────────
results_bias = {}
with h5py.File(DATA_DIR / "gb_bias_results_15.0days.h5", "r") as fh:
    for key in fh.keys():
        results_bias[key] = fh[key][()]

# ── Load response-only mismatch (realistic case, sky-averaged) ───────────────
with h5py.File(EXTRACTED_DIR / "gb_segwo_mismatch.h5", "r") as ds:
    f_resp           = ds["frequencies"][()]
    mean_no_boost    = ds["realistic_no_boost/mismatch_mean_sky_pol0"][()]
    mean_boost       = ds["realistic_boost/mismatch_mean_sky_pol0"][()]

# ── Plot ──────────────────────────────────────────────────────────────────────
labels = {
    "mismatch_perturbed_vs_nominal_with_rel":  "Perturbed vs Nominal Orbits",
    "mismatch_nonrel_vs_rel_with_nominal":     "Non-Boosted vs Boosted Response",
}

plt.figure(figsize=(COL1, COL1))

# GB mismatch: perturbed vs nominal
key = "mismatch_perturbed_vs_nominal_with_rel"
y_mean = mismatch[key].mean(axis=1)
y_min  = mismatch[key].min(axis=1)
y_max  = mismatch[key].max(axis=1)
plt.fill_between(f0_vec, y_min, y_max, alpha=0.2, color='C0')
plt.plot(f0_vec, y_mean, '-', label=labels[key], color='C0')

# GB mismatch: non-boosted vs boosted
key = "mismatch_nonrel_vs_rel_with_nominal"
y_mean = mismatch[key].mean(axis=1)
y_min  = mismatch[key].min(axis=1)
y_max  = mismatch[key].max(axis=1)
plt.fill_between(f0_vec, y_min, y_max, alpha=0.2, color='C1')
plt.plot(f0_vec, y_mean, '-', label=labels[key], color='C1')

# Response-only mismatch
plt.loglog(f_resp, mean_no_boost, ls='--', color='C1')
plt.loglog(f_resp, mean_boost,    ls='--', color='C0')

# Mismatch at best-fit
plt.loglog(results_bias['f0_vec'],
           np.abs(results_bias['mismatch_at_bestfit']), 'C1:')

plt.xscale("log")
plt.yscale("log")
plt.xlabel("Frequency (Hz)")
plt.ylabel(r"Mismatch $\mathcal{M}$")
ax = plt.gca()

style_handles = [
    Line2D([0], [0], color='k', ls='-',  label='Galactic Binary'),
    Line2D([0], [0], color='k', ls=':',  label='Galactic Binary\nMaximized'),
    Line2D([0], [0], color='k', ls='--', label='Response-only'),
]
color_handles = [
    Line2D([0], [0], color='C0', lw=1.5,
           label='Orbit uncertainty: Perturbed vs Nominal'),
    Line2D([0], [0], color='C1', lw=1.5,
           label='Response mismodeling: Boosted vs Non-Boosted'),
]

legend_style = ax.legend(handles=style_handles, title="Model",
                         loc="upper right", title_fontsize=10)
ax.add_artist(legend_style)
ax.legend(handles=color_handles, title="Comparison Effects",
          loc="upper center", bbox_to_anchor=(0.5, 1.3),
          ncol=1, title_fontsize=10, frameon=True, framealpha=0.0)

plt.grid()
plt.tight_layout()
out = OUTPUT_DIR / "gb_mismatch_plot.png"
plt.savefig(out, dpi=300, bbox_inches='tight')
print(f"✓ {out.name}")
plt.show()
