"""
Plot 01 — LISA 3D orbit (LISA + toy static constellation).

Requires:
  reproduce_plots/data/orbit_data.h5   (generated by save_all_data.py)

Outputs:
  reproduce_plots/figures/lisa_orbit.png
  reproduce_plots/figures/toy_orbit.png
"""

from pathlib import Path
import sys
import numpy as np
import h5py

# ── Paths and shared config ───────────────────────────────────────────────────
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent))   # workspace root for plot_utils

from config import apply_style, EXTRACTED_DIR, OUTPUT_DIR
from plot_utils import plot_orbit_3d
from lisaorbits import StaticConstellation

apply_style()

# ── Load data ─────────────────────────────────────────────────────────────────
with h5py.File(EXTRACTED_DIR / "orbit_data.h5", "r") as ds:
    t_orb = ds["t_interp"][()]
    x_orb = ds["x_median"][()]
    v_orb = ds["v_median"][()]
    ltt   = ds["ltt_median"][()]

# ── LISA realistic orbit ──────────────────────────────────────────────────────
orbital_info = {"t": t_orb, "x": x_orb, "v": v_orb, "ltt": ltt}
plot_orbit_3d(
    orbital_info, 1.0,
    output_file=str(OUTPUT_DIR / "lisa_orbit.png"),
    figsize=(6 * 2, 2 * 3.5),
    include_sun=True,
)
print("✓ lisa_orbit.png")

# ── Toy static constellation ──────────────────────────────────────────────────
orbits = StaticConstellation.from_armlengths(2.5e9, 2.5e9, 2.5e9)
orbital_info_toy = {"t": t_orb, "x": orbits.compute_position(t_orb)}
plot_orbit_3d(
    orbital_info_toy, 1.0,
    output_file=str(OUTPUT_DIR / "toy_orbit.png"),
    figsize=(6, 3.5),
    include_sun=False,
)
print("✓ toy_orbit.png")
