"""
Plot 07 — Mismatch vs GW frequency for all perturbation types.

Requires:
  reproduce_plots/data/mismatch_frequency_data.h5   (generated by save_all_data.py)

Output:
  reproduce_plots/figures/mismatch_vs_frequency.pdf
"""

from pathlib import Path
import sys
import numpy as np
import h5py
import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from config import apply_style, EXTRACTED_DIR, OUTPUT_DIR, COLORBLIND_PALETTE, COL2, POLS

apply_style()

# ── Load data ─────────────────────────────────────────────────────────────────
with h5py.File(EXTRACTED_DIR / "mismatch_frequency_data.h5", "r") as ds:
    f = ds["frequencies"][()]
    data = {}
    for key in ds.keys():
        if key == "frequencies":
            continue
        data[key] = {
            "mismatch_mean": ds[f"{key}/mismatch_mean"][()],
            "mismatch_min":  ds[f"{key}/mismatch_min"][()],
            "mismatch_max":  ds[f"{key}/mismatch_max"][()],
        }

# ── Style map (group name → display label + style) ───────────────────────────
STYLES = {
    "arm-length_boost":    dict(label="Arm-length",   color=COLORBLIND_PALETTE[0], ls="--", lw=1.3),
    "rotation_boost":      dict(label="Rotation",     color=COLORBLIND_PALETTE[1], ls="--", lw=1.3),
    "translation_boost":   dict(label="Translation",  color=COLORBLIND_PALETTE[2], ls="--", lw=1.3),
    "realistic_boost":     dict(label="Realistic",    color="k",                    ls="-",  lw=1.3),
}

# ── Plot ──────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(COL2, 2.8), sharex=True, sharey=True)

for grp_key, style in STYLES.items():
    if grp_key not in data:
        continue
    d         = data[grp_key]
    freq_mean = d["mismatch_mean"]   # (F, 2)
    freq_min  = d["mismatch_min"]
    freq_max  = d["mismatch_max"]

    for j, ax in enumerate(axes):
        ax.fill_between(f, freq_min[:, j], freq_max[:, j],
                        color=style["color"], alpha=0.12)
        ax.plot(f, freq_mean[:, j],
                ls=style["ls"], lw=style["lw"], color=style["color"],
                label=style["label"] if j == 0 else None)

for j, ax in enumerate(axes):
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Frequency [Hz]")
    ax.set_ylabel(r"Mismatch $\mathcal{M}$")
    ax.set_title(POLS[j])
    ax.set_ylim(bottom=1e-18)

axes[0].legend(fontsize=7, ncol=1, loc="upper left")
plt.tight_layout()
out = OUTPUT_DIR / "mismatch_vs_frequency.pdf"
plt.savefig(out)
print(f"✓ {out.name}")
plt.show()
