"""
Plot 06 — Amplitude and phase errors vs GW frequency.

Compares mismodeling (non-boosted) and orbit-uncertainty (boosted) cases
for the realistic 15-day observation.

Requires:
  reproduce_plots/data/amplitude_phase_errors.h5   (generated by save_all_data.py)

Output:
  reproduce_plots/figures/amplitude_phase_errors.png
"""

from pathlib import Path
import sys
import numpy as np
import h5py
import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from config import apply_style, EXTRACTED_DIR, OUTPUT_DIR, COL1

apply_style()

# ── Load data ─────────────────────────────────────────────────────────────────
with h5py.File(EXTRACTED_DIR / "amplitude_phase_errors.h5", "r") as ds:
    f = ds["frequencies"][()]

    amp_mean_nb   = ds["realistic_no_boost/amp_mean"][()]     # (F, 3, 2)
    amp_min_nb    = ds["realistic_no_boost/amp_min"][()]
    amp_max_nb    = ds["realistic_no_boost/amp_max"][()]
    angle_mean_nb = ds["realistic_no_boost/angle_mean"][()]
    angle_min_nb  = ds["realistic_no_boost/angle_min"][()]
    angle_max_nb  = ds["realistic_no_boost/angle_max"][()]

    amp_mean_b    = ds["realistic_boost/amp_mean"][()]
    amp_min_b     = ds["realistic_boost/amp_min"][()]
    amp_max_b     = ds["realistic_boost/amp_max"][()]
    angle_mean_b  = ds["realistic_boost/angle_mean"][()]
    angle_min_b   = ds["realistic_boost/angle_min"][()]
    angle_max_b   = ds["realistic_boost/angle_max"][()]

# ── Plot ──────────────────────────────────────────────────────────────────────
ch, pol = 0, 0
labels    = ['Mismodeling', 'Orbit uncertainties']
linestyle = ['-', '--']

datasets = [
    (amp_mean_nb, amp_min_nb, amp_max_nb,
     angle_mean_nb, angle_min_nb, angle_max_nb),
    (amp_mean_b,  amp_min_b,  amp_max_b,
     angle_mean_b,  angle_min_b,  angle_max_b),
]

fig, axs = plt.subplots(2, 1, figsize=(COL1, 1.2 * COL1), sharex=True)

for i, (am, amin, amax, phm, phmin, phmax) in enumerate(datasets):
    # Amplitude
    axs[0].fill_between(f, amin[:, ch, pol], amax[:, ch, pol],
                        alpha=0.2, color=f'C{i}')
    axs[0].loglog(f, am[:, ch, pol], label=labels[i],
                  color=f'C{i}', linestyle=linestyle[i])
    # Phase
    axs[1].fill_between(f, phmin[:, ch, pol], phmax[:, ch, pol],
                        alpha=0.2, color=f'C{i}')
    axs[1].loglog(f, phm[:, ch, pol], label=labels[i],
                  color=f'C{i}', linestyle=linestyle[i])

axs[0].axhline(1e-4, color='r', ls=':', lw=1.2, label="Reference level")
axs[0].set_ylabel("Amplitude Relative \nDifference")
axs[0].loglog(f, 1e-5 / f, color='k', ls=linestyle[0], lw=1.2,
              label=r"$\propto f^{-1}$", alpha=0.5)
axs[0].loglog(f, 1e-5 * f, color='k', ls=linestyle[1], lw=1.2,
              label=r"$\propto f$", alpha=0.5)
axs[0].legend(ncol=2, title_fontsize=10, bbox_to_anchor=(1., 1.5))
axs[0].set_ylim(0.5e-7, 5)

axs[1].set_xlabel("Frequency [Hz]")
axs[1].set_ylabel("Phase Absolute \nDifference [rad]")
axs[1].axhline(1e-2, color='r', ls=':', lw=1.2, label="Reference level")

plt.tight_layout()
out = OUTPUT_DIR / "amplitude_phase_errors.png"
plt.savefig(out, dpi=300)
print(f"✓ {out.name}")
plt.show()
